### ISSUE TITLE
Graceful approach to getting @odata_id of a nonexisting resource required

### ISSUE THREAD

**Issue by matejart** [xlab-steampunk/redfish-client-python#25]
# The problem

Assuming we have a resource that looks like this:

```
{
    "@odata.context": "/redfish/v1/$metadata#SmcFirmwareInventory.SmcFirmwareInventory",
    "@odata.type": "#SmcFirmwareInventory.v1_0_0.SmcFirmwareInventory",
    "@odata.id": "/redfish/v1/UpdateService/SmcFirmwareInventory/BIOS",
    "Id": "BIOS",
    "Name": "SUPERMICRO BIOS",
    "Description": "Description of SUPERMICRO BIOS",
    "Updatable": true,
    "VersionSequence": "BIOS Date:  <Date> Rev <major>.<minor>",
    "Version": "BIOS Date:  11/22/2019 Rev 2.1",
    "RelatedItem": [
        {
            "@odata.id": "/redfish/v1/Systems/1/Bios"
        }
    ],
    "Actions": {
        "Oem": {},
        "#SmcFirmwareInventory.EnterUpdateMode": {
            "target": "/redfish/v1/UpdateService/SmcFirmwareInventory/BIOS/Actions/SmcFirmwareInventory.EnterUpdateMode"
        }
    },
    "Oem": {}
}
```

We are interested in the resource in the `RelatedItem` list. However, the resource being referenced by that JSON pointer does not exist:

```
>>> root.find('/redfish/v1/Systems/1/Bios').raw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 186, in raw
    return self._get_content()
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 110, in _get_content
    self._headers, self._content = self._init_from_oid(oid)
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 66, in _init_from_oid
    raise ResourceNotFound(resp.raw)
```

So even if we are only interested in the value of the `@odata.id` of that pointer, there seems to be no good way to get it at the resources. In particular, the following fails:

```
>>> related_item = root.UpdateService.Oem.Supermicro.SmcFirmwareInventory.Members[1].RelatedItem[0]
>>> related_item["@odata.id"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 102, in __getitem__
    return self._build(self._get_content()[name])
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 110, in _get_content
    self._headers, self._content = self._init_from_oid(oid)
  File "/home/matej/Projekti/Mojo/coordinator/.venv/lib/python3.6/site-packages/redfish_client/resource.py", line 66, in _init_from_oid
    raise ResourceNotFound(resp.raw)
redfish_client.exceptions.ResourceNotFound
```

# Suggested solution

In `Resource`, expose a property such as `name` to be accessible without any evaluation attempts.

**Comment by tadeboro** [comment]
Exposing a `name` or an `id`  property is not the best idea here since not all resources have names and ids. I would instead propose that we make the resources attribute access lazy. This will allow us to keep the API intact while still allowing us to access parts of data that do not exist on the remote.
